name: json-yaml-validate
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-signals:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout schemas repo
        uses: actions/checkout@v4
        with:
          repository: OBDb/.schemas
          path: .schemas

      - name: Validate signalsets
        id: json-yaml-validate-v3
        uses: GrantBirki/json-yaml-validate@v2.7.1
        with:
          comment: "true"
          base_dir: signalsets/v3/
          json_schema: .schemas/signals.json
